# Generated by Django 5.2.17 on 2026-08-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccosettings',
            name='loan_interest_rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
