# Generated by Django 5.2.17 on 2026-08-24 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog_saccosettings'),
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('Airtel', 'Airtel Money')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('internal_reference', models.CharField(max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sacco_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Failed', 'Failed'), ('Duplicate', 'Duplicate'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('source', models.CharField(choices=[('SMS', 'SMS'), ('Provider API', 'Provider API'), ('Admin verification', 'Admin verification')], default='SMS', max_length=30)),
                ('provider_verified', models.BooleanField(default=False)),
                ('sms_received', models.BooleanField(default=False)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.member')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'transaction_id'), name='unique_provider_transaction')],
            },
        ),
    ]
