# Generated by Django 5.2.17 on 2026-08-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
