# Generated by Django 5.2.17 on 2026-09-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_payment_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('Airtel', 'Airtel Money'), ('PesaPal', 'PesaPal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='savings',
            name='payment_method',
            field=models.CharField(choices=[('MTN Mobile Money', 'MTN Mobile Money'), ('Airtel Money', 'Airtel Money'), ('Manual deposit', 'Manual deposit')], max_length=30),
        ),
    ]
