# Generated by Django 5.2.17 on 2026-08-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_approved_at_loan_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
